### ISSUE TITLE
AOSv2 Data proxy Credential not listed

### ISSUE THREAD

**Issue by mzur** [ArunaStorage/website#68]
In the AOSv2 web UI, if I create new credentials for a data proxy, there is a modal that shows the credentials but once the modal is dismissed, the credentials cannot be modified. I would expect there to be a list of current credentials that allows me to revoke individual credentials or add new ones. Instead, I get the same credentials each time I click on "create credential".

**Comment by St4NNi** [comment]
Hi Martin, thanks for the issue, i have transferred this to the ArunaWeb repo since this issue is related to the WebUI.

The implementation / representation of Dataproxy credentials in the web-ui is currently very limited. The WebUI only supports the creation & retrieval of personal S3 credentials without any revoke options, this will hopefully be addressed in one of the next releases.

You can work around this issue if you use an aruna token to create S3 credentials via the API directly. This will bind the S3Credentials to your token and will automatically revoke the credentials when you revoke the token. A more explicit revoke option including a list of all current credentials will follow soon.

I will keep this issue open as a reminder and will come back when the update is live.

BR
Sebastian

**Comment by mzur** [comment]
Will the S3 credentials also respect the permissions configured for the Aruna token?

**Comment by St4NNi** [comment]
Yes. Credentials associated with a specific token are limited to actions permitted by the token's scope.

**Comment by mzur** [comment]
Alright, thanks!
